config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "books#index"

  resources :books
  # get "/books", to: "books#index"
  # post "/books", to: "books#create"
  # get "/books/new", to: "books#new", as: "new_book"
  # get "/books/:id/edit", to: "books#edit", as: "edit_book"
  # get "/books/:id", to: "books#show", as: "book"
  # put "/books/:id", to: "books#update"
  # delete "/books/:id", to: "books#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title, presence: true
    validates :author, presence: true
    validates :status, presence:true
    validates :rating, numericality: {less_than_or_equal_to: 5, more_than_or_equal_to: 1}, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :set_book, only: [:show, :edit, :update, :destroy]

    def index
        @books = Book.all
    end

    def show
    end

    def new
        @book = Book.new
    end

    def create
        @book = Book.new(book_params)

        if @book.save
            redirect_to @book
        else
            render:new
        end
    end

    def edit
    end

    def update
        if @book.update(book_params)
            redirect_to @book, notice: "Book was successfully updated"
        else
            render :edit
        end
    end

    def destroy
        @book.destroy
        redirect_to books_url, notice: 'Book was successfully removed.'
    end

    private

        def set_book
            @book = Book.find(params[:id])
        end

        def book_params
            params.require(:book).permit(:title, :author, :status, :rating, :cover_url)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model: @book, class: "book-form" do |form| %>
  <div class="mb-3">
    <%= form.label :title, class: "form-label" %><br>
    <%= form.text_field :title, class: "form-control" %>
    <% book.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="mb-3">
    <%= form.label :author, class: "form-label" %><br>
    <%= form.text_field :author, class: "form-control" %>
    <% book.errors.full_messages_for(:author).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="mb-3 row g-3 align-items-center">
    <div class="col-auto">
      <%= form.label :status, class: "col-form-label" %><br>
    </div>

    <div class="col-auto">
      <%= form.select :status, [["To Be Read", "tbr"], ["Currently Reading", "reading"], ["Read", "read"]] %>
    </div>

    <div class="col-auto">
      <% book.errors.full_messages_for(:status).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  </div>

  <div class="mb-3 row g-3 align-items-center">
    <div class="col-auto">
      <%= form.label :rating, class: "col-form-label" %><br>
    </div>

    <div class="col-auto">
      <%= form.select :rating, [["Select", nil],["1/5", 1], ["2/5", 2], ["3/5", 3], ["4/5", 4], ["5/5", 5]] %>
    </div>

    <div class="col-auto">
      <% book.errors.full_messages_for(:rating).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :cover_url, class: "form-label" %><br>
    <%= form.text_field :cover_url, class: "form-control" %>
    <% book.errors.full_messages_for(:cover_url).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit btn_label, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/books/_header.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to books_path, class: "navbar-brand" do %>
        <i class="bi bi-eyeglasses"></i> The Bookish Worm
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <%= link_to "All Books", books_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Add a Book", new_book_path, class: "nav-link" %>
            </li>
        </ul>
    </div>
  </div>
</nav>

app/views/books/edit.html.erb
<%= render "header" %>

<div class="page-label">
    <h1>Edit Book</h1>
</div>

<%= render "form", book: @book, btn_label: "Update Book" %>

app/views/books/index.html.erb
<%= render "header" %>

<div class="page-label">
    <h1>All Books</h1>
    <%= link_to "Add a Book",  new_book_path, class: "btn btn-primary"%>
</div>

<% flash.each do |msg| %>
  <div class="alert alert-info">
    <%= msg %>
  </div>
<% end %>

<div class="row book-list">
    <% @books.each do |book| %>
        <div class="col-sm">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title"><%= book.title %></h5>
                    <p class="card-text"><%= book.author %></p>
                    <%= link_to book_path(book.id), class: "btn btn-secondary" do %>
                        <i class="bi bi-eye-fill"></i> View
                    <% end %>
                    <%= link_to edit_book_path(book.id), class: "btn btn-secondary" do %>
                        <i class="bi bi-pencil-fill"></i> Edit
                    <% end %>
                    <%= link_to book_path(book.id), class: "btn btn-secondary", method: :delete, data: {
                                                confirm: "Are you sure?"
                                                } do %>
                        <i class="bi bi-trash-fill"></i> Delete
                    <% end %>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/books/new.html.erb
<%= render "header" %>

<div class="page-label">
    <h1>Add a Book</h1>
</div>

<%= render "form", book: @book, btn_label: "Add Book" %>

app/views/books/show.html.erb
<%= render "header" %>

<% flash.each do |type, msg| %>
  <div class="alert alert-info">
    <%= msg %>
  </div>
<% end %>

<div class="container show-book">
    <div class="row">
        <div class="col book-cover">
            <%= if !@book.cover_url || @book.cover_url.empty?;1.times do %>
                    <%= image_tag "https://media.istockphoto.com/vectors/no-image-available-icon-vector-id1216251206?k=6&m=1216251206&s=612x612&w=0&h=G8kmMKxZlh7WyeYtlIHJDxP5XRGm9ZXyLprtVJKxd-o="%>
                <% end %>
                <% nil
            elsif !@book.cover_url.empty?; 1.times do%>
                    <%= image_tag @book.cover_url%>
                <% end %>
                <% nil %>
            <% end %>
        </div>
        <div class="col book-details">
            <h1 class="title"><%= @book.title %></h1>
            <h3 class="author">By: <%= @book.author %></h3>

            <div class="book-options">
                <%= link_to edit_book_path(@book.id), class: "btn btn-primary" do %>
                    <i class="bi bi-pencil-fill"></i> Edit
                <% end %>
                <%= link_to book_path(@book.id), class: "btn btn-primary", method: :delete, data: {
                                        confirm: "Are you sure?"
                                        } do %>
                    <i class="bi bi-trash-fill"></i> Delete
                <% end %>
            </div>

            <div class="status">
                <p>Status: <%=
                    case @book.status
                        when "read"
                            "Read"
                        when "reading"
                            "Currently Reading"
                        when "tbr"
                            "To Be Read"
                    end
                %></p>
            </div>

            <div class="rating">
                <p>Rating:
                    <%= if !@book.rating
                            "Not rated yet"
                        else @book.rating.to_i.times do %>
                            <i class="bi bi-star-fill"></i>
                        <% end %>
                        <%= nil %>
                    <% end %>
                </p>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Bookish Worm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>